title: ICLR 2023 Workshop on Physics for Machine Learning
description: Physics4ML

# timezone: America/Toronto

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Speakers: "/speakers"
  Organizers: "/organizers"
  Program Committee: "/committee"
  Accepted Papers: "/papers"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', vendor]
